### ISSUE TITLE
[Bug Report] Unintended Resume Prompt after Video Preview

### ISSUE THREAD

**Issue by VampireChicken12** [YouTube-Enhancer/extension#205]
**Description:**
When a video is previewed by hovering over its thumbnail and subsequently clicked to watch, an unintended resume prompt appears. This behavior is unexpected as the user hasn't watched the video before, and there shouldn't be a resume prompt for a video that has only been previewed.

**Steps to Reproduce:**
1. Hover over the thumbnail of a video without clicking to watch it (preview the video).
2. Click on the same video to watch it.

**Expected Behavior:**
After clicking on a video that has only been previewed, it should start from the beginning, and there shouldn't be a resume prompt since the user hasn't watched the video before.

**Actual Behavior:**
An unintended resume prompt appears, asking the user to resume playback, even though the video has only been previewed and not watched before.

**Additional Information:**
- Browser/Platform: Firefox, Chrome, Edge/Windows 10

This bug affects the user experience by introducing confusion when navigating through videos that have been previewed but not watched.

**Comment by rado84-github** [comment]
This bug has either been fixed since you reported it or I simply can't replicate it, no matter how many times I try.
