### ISSUE TITLE
[Bug, maybe] Settings page autoscrolls down when clicking a function to enable or disable

### ISSUE THREAD

**Issue by rado84-github** [YouTube-Enhancer/extension#354]
**Describe the bug**
Settings page autoscrolls down when clicking a function to enable or disable

**To Reproduce**

As always, a video demonstration is a lot better than steps. Simply observe what happens when I click on a function to enable or disable it:

[simplescreenrecorder-2024-02-18_13.36.51.zip](https://github.com/VampireChicken12/youtube-enhancer/files/14322311/simplescreenrecorder-2024-02-18_13.36.51.zip)

**Expected behavior**
Settings page shouldn't move on its own when clicking a function.

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox 122.0.1
- Version: 1.23.3

**Additional context**
IDK if it's a bug or intentional but either way it's confusing and annoying and IMO it shouldn't be happening.

**Comment by VampireChicken12** [comment]
I'm unable to reproduce this issue. I will do more testing and see if I can get it to be reproduced

**Comment by VampireChicken12** [comment]
@rado84-github does this still happen?
