### ISSUE TITLE
[Bug Report] Your file couldn’t be accessed It may have been moved, edited, or deleted. ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by YashSoPro** [YouTube-Enhancer/extension#361]
**Describe the bug**
I'm getting this when I click on the extension
Your file couldn’t be accessed may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND When I re-launch Chrome the extension disappears

**To Reproduce**

1. Go to 'chrome
2. Click on 'enhancer for youtube'
3.  See error

**Expected behavior**
Your file couldn’t be accessed may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND

**Screenshots**

**Desktop (please complete the following information):**

- Browser [Chrome]
- Version [1.22.3]

**Additional context**

**Comment by VampireChicken12** [comment]
@YashSoPro can you upload a video showing you trying to import the settings for the extension on your browser?

**Comment by YashSoPro** [comment]
> @YashSoPro can you upload a video showing you trying to import the settings for the extension on your browser?

lol when i tried to do it again while recording for you it got fixed automatically i dont know how if i will need help again i will create a new issue for now its fixed

**Comment by VampireChicken12** [comment]
> > @YashSoPro can you upload a video showing you trying to import the settings for the extension on your browser?
> 
> lol when i tried to do it again while recording for you it got fixed automatically i dont know how if i will need help again i will create a new issue for now its fixed

Okay thanks for commenting

**Comment by YashSoPro** [comment]
> > > @YashSoPro can you upload a video showing you trying to import the settings for the extension on your browser?
> > 
> > 
> > lol when i tried to do it again while recording for you it got fixed automatically i dont know how if i will need help again i will create a new issue for now its fixed
> 
> Okay thanks for commenting

its showing again
![Screenshot 2024-02-26 091823](https://github.com/VampireChicken12/youtube-enhancer/assets/105553471/d01109fc-c446-431b-9deb-b9e5c91428f5)

**Comment by VampireChicken12** [comment]
> > > > @YashSoPro can you upload a video showing you trying to import the settings for the extension on your browser?
> > > 
> > > 
> > > lol when i tried to do it again while recording for you it got fixed automatically i dont know how if i will need help again i will create a new issue for now its fixed
> > 
> > 
> > Okay thanks for commenting
> 
> its showing again ![Screenshot 2024-02-26 091823](https://private-user-images.githubusercontent.com/105553471/307658238-d01109fc-c446-431b-9deb-b9e5c91428f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTk2NTgsIm5iZiI6MTcwODkxOTM1OCwicGF0aCI6Ii8xMDU1NTM0NzEvMzA3NjU4MjM4LWQwMTEwOWZjLWM0NDYtNDMxYi05ZGViLWI5ZTVjOTE0MjhmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwMzQ5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzBlNzgyMmMyNTAzM2Q4ZDdkYjZkOTQ3Y2Y1Nzc3YWMyZDEzZDE3Mzk4YmEzYWVhMzI1ZGM1NTJiMzExOTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i3Ws7HHS4ovzoyzMvChTJ9Dl_K4cs3rjw5LDrD4HnTk)

Hmm that's really weird. can you tell me what version of chrome you are using and what version of the extension you are using? Also are you using a pre-bundled extension or did you build the extension yourself?

**Comment by YashSoPro** [comment]
> > > > > @YashSoPro can you upload a video showing you trying to import the settings for the extension on your browser?
> > > > 
> > > > 
> > > > lol when i tried to do it again while recording for you it got fixed automatically i dont know how if i will need help again i will create a new issue for now its fixed
> > > 
> > > 
> > > Okay thanks for commenting
> > 
> > 
> > its showing again ![Screenshot 2024-02-26 091823](https://private-user-images.githubusercontent.com/105553471/307658238-d01109fc-c446-431b-9deb-b9e5c91428f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTk2NTgsIm5iZiI6MTcwODkxOTM1OCwicGF0aCI6Ii8xMDU1NTM0NzEvMzA3NjU4MjM4LWQwMTEwOWZjLWM0NDYtNDMxYi05ZGViLWI5ZTVjOTE0MjhmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwMzQ5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzBlNzgyMmMyNTAzM2Q4ZDdkYjZkOTQ3Y2Y1Nzc3YWMyZDEzZDE3Mzk4YmEzYWVhMzI1ZGM1NTJiMzExOTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i3Ws7HHS4ovzoyzMvChTJ9Dl_K4cs3rjw5LDrD4HnTk)
> 
> Hmm that's really weird. can you tell me what version of chrome you are using and what version of the extension you are using? Also are you using a pre-built archive of the extension or did you build the extension yourself?

Updating Chrome (20%)
Version 121.0.6167.189 (Official Build) (64-bit)
 extension version is latest

**Comment by YashSoPro** [comment]
> > > > > @YashSoPro can you upload a video showing you trying to import the settings for the extension on your browser?
> > > > 
> > > > 
> > > > lol when i tried to do it again while recording for you it got fixed automatically i dont know how if i will need help again i will create a new issue for now its fixed
> > > 
> > > 
> > > Okay thanks for commenting
> > 
> > 
> > its showing again ![Screenshot 2024-02-26 091823](https://private-user-images.githubusercontent.com/105553471/307658238-d01109fc-c446-431b-9deb-b9e5c91428f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTk2NTgsIm5iZiI6MTcwODkxOTM1OCwicGF0aCI6Ii8xMDU1NTM0NzEvMzA3NjU4MjM4LWQwMTEwOWZjLWM0NDYtNDMxYi05ZGViLWI5ZTVjOTE0MjhmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwMzQ5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzBlNzgyMmMyNTAzM2Q4ZDdkYjZkOTQ3Y2Y1Nzc3YWMyZDEzZDE3Mzk4YmEzYWVhMzI1ZGM1NTJiMzExOTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i3Ws7HHS4ovzoyzMvChTJ9Dl_K4cs3rjw5LDrD4HnTk)
> 
> Hmm that's really weird. can you tell me what version of chrome you are using and what version of the extension you are using? Also are you using a pre-built archive of the extension or did you build the extension yourself?

no i didnt build it idk how to lol

**Comment by VampireChicken12** [comment]
> > > > > > @YashSoPro can you upload a video showing you trying to import the settings for the extension on your browser?
> > > > > 
> > > > > 
> > > > > lol when i tried to do it again while recording for you it got fixed automatically i dont know how if i will need help again i will create a new issue for now its fixed
> > > > 
> > > > 
> > > > Okay thanks for commenting
> > > 
> > > 
> > > its showing again ![Screenshot 2024-02-26 091823](https://private-user-images.githubusercontent.com/105553471/307658238-d01109fc-c446-431b-9deb-b9e5c91428f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTk2NTgsIm5iZiI6MTcwODkxOTM1OCwicGF0aCI6Ii8xMDU1NTM0NzEvMzA3NjU4MjM4LWQwMTEwOWZjLWM0NDYtNDMxYi05ZGViLWI5ZTVjOTE0MjhmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwMzQ5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzBlNzgyMmMyNTAzM2Q4ZDdkYjZkOTQ3Y2Y1Nzc3YWMyZDEzZDE3Mzk4YmEzYWVhMzI1ZGM1NTJiMzExOTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i3Ws7HHS4ovzoyzMvChTJ9Dl_K4cs3rjw5LDrD4HnTk)
> > 
> > 
> > Hmm that's really weird. can you tell me what version of chrome you are using and what version of the extension you are using? Also are you using a pre-built archive of the extension or did you build the extension yourself?
> 
> Updating Chrome (20%) Version 121.0.6167.189 (Official Build) (64-bit) extension version is latest

thanks let me look into it.

**Comment by YashSoPro** [comment]
> > > > > > > @YashSoPro can you upload a video showing you trying to import the settings for the extension on your browser?
> > > > > > 
> > > > > > 
> > > > > > lol when i tried to do it again while recording for you it got fixed automatically i dont know how if i will need help again i will create a new issue for now its fixed
> > > > > 
> > > > > 
> > > > > Okay thanks for commenting
> > > > 
> > > > 
> > > > its showing again ![Screenshot 2024-02-26 091823](https://private-user-images.githubusercontent.com/105553471/307658238-d01109fc-c446-431b-9deb-b9e5c91428f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTk2NTgsIm5iZiI6MTcwODkxOTM1OCwicGF0aCI6Ii8xMDU1NTM0NzEvMzA3NjU4MjM4LWQwMTEwOWZjLWM0NDYtNDMxYi05ZGViLWI5ZTVjOTE0MjhmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwMzQ5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzBlNzgyMmMyNTAzM2Q4ZDdkYjZkOTQ3Y2Y1Nzc3YWMyZDEzZDE3Mzk4YmEzYWVhMzI1ZGM1NTJiMzExOTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i3Ws7HHS4ovzoyzMvChTJ9Dl_K4cs3rjw5LDrD4HnTk)
> > > 
> > > 
> > > Hmm that's really weird. can you tell me what version of chrome you are using and what version of the extension you are using? Also are you using a pre-built archive of the extension or did you build the extension yourself?
> > 
> > 
> > no i didnt build it idk how to lol
> 
> okay

hmm any idea to fix

**Comment by VampireChicken12** [comment]
> > > > > > > > @YashSoPro can you upload a video showing you trying to import the settings for the extension on your browser?
> > > > > > > 
> > > > > > > 
> > > > > > > lol when i tried to do it again while recording for you it got fixed automatically i dont know how if i will need help again i will create a new issue for now its fixed
> > > > > > 
> > > > > > 
> > > > > > Okay thanks for commenting
> > > > > 
> > > > > 
> > > > > its showing again ![Screenshot 2024-02-26 091823](https://private-user-images.githubusercontent.com/105553471/307658238-d01109fc-c446-431b-9deb-b9e5c91428f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTk2NTgsIm5iZiI6MTcwODkxOTM1OCwicGF0aCI6Ii8xMDU1NTM0NzEvMzA3NjU4MjM4LWQwMTEwOWZjLWM0NDYtNDMxYi05ZGViLWI5ZTVjOTE0MjhmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwMzQ5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzBlNzgyMmMyNTAzM2Q4ZDdkYjZkOTQ3Y2Y1Nzc3YWMyZDEzZDE3Mzk4YmEzYWVhMzI1ZGM1NTJiMzExOTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i3Ws7HHS4ovzoyzMvChTJ9Dl_K4cs3rjw5LDrD4HnTk)
> > > > 
> > > > 
> > > > Hmm that's really weird. can you tell me what version of chrome you are using and what version of the extension you are using? Also are you using a pre-built archive of the extension or did you build the extension yourself?
> > > 
> > > 
> > > no i didnt build it idk how to lol
> > 
> > 
> > okay
> 
> hmm any idea to fix

I'm not sure at the moment.

**Comment by VampireChicken12** [comment]
Dear @YashSoPro,

Thank you for bringing up your concerns. I wanted to inform you and the community that I am currently facing a personal commitment as my dog is expected to give birth any minute now. Due to this, my availability for testing and addressing issues may be limited for the next 8 weeks.

I understand the importance of the issue you raised, and I appreciate your patience. I'll do my best to catch up on any pending tasks as soon as possible. If there are urgent matters that need immediate attention, please feel free to bring them to my notice, and I'll try to assist remotely when I can.

Thank you for your understanding.

Best regards,
VampireChicken

**Comment by YashSoPro** [comment]
> Dear @YashSoPro,
> 
> Thank you for bringing up your concerns. I wanted to inform you and the community that I am currently facing a personal commitment as my dog is expected to give birth any minute now. Due to this, my availability for testing and addressing issues may be limited for the next 8 weeks.
> 
> I understand the importance of the issue you raised, and I appreciate your patience. I'll do my best to catch up on any pending tasks as soon as possible. If there are urgent matters that need immediate attention, please feel free to bring them to my notice, and I'll try to assist remotely when I can.
> 
> Thank you for your understanding.
> 
> Best regards, VampireChicken

that's ok

**Comment by VampireChicken12** [comment]
> > Dear @YashSoPro,
> > Thank you for bringing up your concerns. I wanted to inform you and the community that I am currently facing a personal commitment as my dog is expected to give birth any minute now. Due to this, my availability for testing and addressing issues may be limited for the next 8 weeks.
> > I understand the importance of the issue you raised, and I appreciate your patience. I'll do my best to catch up on any pending tasks as soon as possible. If there are urgent matters that need immediate attention, please feel free to bring them to my notice, and I'll try to assist remotely when I can.
> > Thank you for your understanding.
> > Best regards, VampireChicken
> 
> that's ok

thanks for understanding

**Comment by livingflore** [comment]
tested on chromium, works fine

![изображение](https://github.com/VampireChicken12/youtube-enhancer/assets/63370734/717401f9-7bfa-439d-84c7-ef379d46d35e)

@YashSoPro is it still a problem?

**Comment by YashSoPro** [comment]
> tested on chromium, works fine
> 
> ![изображение](https://private-user-images.githubusercontent.com/63370734/315757706-717401f9-7bfa-439d-84c7-ef379d46d35e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzM0ODUsIm5iZiI6MTcxMTA3MzE4NSwicGF0aCI6Ii82MzM3MDczNC8zMTU3NTc3MDYtNzE3NDAxZjktN2JmYS00MzlkLTg0YzctZWYzNzlkNDZkMzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDAyMDYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNTM2YjdiOTNjOGNmNjE2YjI3OWRjM2I5MDMwOTM3M2QwOTZmYTllZmJmYzk2NjA1ZjY1NDllYmI5NGU1YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tMrxiuDrw0NF0hgULtVzCLWttNEWYzhRFfzlWlvR4Lk)
> 
> @YashSoPro is it still a problem?

try on chrome normal one latest version

**Comment by livingflore** [comment]
> try on chrome normal one latest version

![изображение](https://github.com/VampireChicken12/youtube-enhancer/assets/63370734/8af61337-c0ed-4338-9ce7-66045ed64781)

chrome 123

**Comment by YashSoPro** [comment]
ahh

> > try on chrome normal one latest version
> 
> ![изображение](https://private-user-images.githubusercontent.com/63370734/315966522-8af61337-c0ed-4338-9ce7-66045ed64781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDE4ODMsIm5iZiI6MTcxMTEwMTU4MywicGF0aCI6Ii82MzM3MDczNC8zMTU5NjY1MjItOGFmNjEzMzctYzBlZC00MzM4LTljZTctNjYwNDVlZDY0NzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5NTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZGU1YWQxNDIyODRhMmVmMThlM2RmMGUxMTZmMTdmNjQzMTlkZjViZDY4ZWM5NDZjNjAyNTZjN2NmMzdiNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3i2TneLaz7q_2Hz6QZyaWZMu6kn8VNaTw4H1rgHfSX0)
> 
> chrome 123

ahh idk why it didn't worked for me I'll try again

**Comment by VampireChicken12** [comment]
it's possible where the extension was extracted was deleted. When I am developing the extension if the build is interrupted sometimes not all of the files are output so the browser can't find the file.

**Comment by YashSoPro** [comment]
> it's possible where the extension was extracted was deleted. When I am developing the extension if the build is interrupted sometimes not all of the files are output so the browser can't find the file.

can be but I'll give it a try

**Comment by VampireChicken12** [comment]
@YashSoPro are you still having an issue with this? If not I will close the issue
