### ISSUE TITLE
[Feature Request] Disable info cards/end screens visibility

### ISSUE THREAD

**Issue by charlymoon741** [YouTube-Enhancer/extension#373]
I would like an option to get rid of the end cards or video recommendations that appear at the end of the videos, it is a big issue on videos that don't have an outro

screenshots for how a before and after result would look like

Before
![image](https://github.com/VampireChicken12/youtube-enhancer/assets/62484941/441bdf40-b2a1-4148-bbf6-4dae244ec94f)
After
![image](https://github.com/VampireChicken12/youtube-enhancer/assets/62484941/13b98af1-2d48-430a-a71c-c263d1011ca1)

**Comment by VampireChicken12** [comment]
@charlymoon741 Do you think this still deserves it's own feature?

**Comment by VampireChicken12** [comment]
@all-contributors please add @charlymoon741 for ideas

**Comment by VampireChicken12** [comment]
@all-contributors please add @charlymoon741 for ideas

**Comment by VampireChicken12** [comment]
@all-contributors please add @charlymoon741 for ideas

**Comment by slrgt** [comment]
Can the End Screen Cards option also be available as a button that can be clicked on\off similar to the speed and screenshot buttons under the player? Would help for the videos that don't have an outro and for the videos that sometimes have useful screen cards

**Comment by VampireChicken12** [comment]
> Can the End Screen Cards option also be available as a button that can be clicked on\off similar to the speed and screenshot buttons under the player? Would help for the videos that don't have an outro and for the videos that sometimes have useful screen cards

Sure can you make a new issue for this feature

**Comment by slrgt** [comment]
Done :)

**Comment by VampireChicken12** [comment]
Thanks
