### ISSUE TITLE
Scroll Wheel Volume Control Settings don't work on YouTube's new interface

### ISSUE THREAD

**Issue by VictorJulianiR** [YouTube-Enhancer/extension#410]
**Describe the bug**
Scroll Wheel Volume Control Settings is not working on the new interface, even if the option to work only a modifier key is pressed.

**To Reproduce**

1. Go to any video.
2. Click on the video, so the context is correct.
3. Scroll down or up
4. See volume doesn't change as the page scrolls up and down.

**Expected behavior**
Volume should change.

**Desktop (please complete the following information):**

- OS: WIN11
- Browser Opera
- Version LVL5 (core: 107.0.5045.86)

**Comment by VampireChicken12** [comment]
I don't have the new UI yet so expect things to break. I'll fix them as soon as possible

**Comment by VictorJulianiR** [comment]
New UI sucks. The old one is better in so many ways. It's just to push more shorts or more watchtime, but I actually made things worse.

**Comment by VampireChicken12** [comment]
> New UI sucks. The old one is better in so many ways. It's just to push more shorts or more watchtime, but I actually made things worse.

Agreed it is worse, From what I have seen online I am counting the days of having the old ui.

**Comment by livingflore** [comment]
you can revert to the old UI by those ublock filters, this is temporary solution though:
```
www.youtube.com##+js(set, yt.config_.EXPERIMENT_FLAGS.kevlar_watch_grid, false)
www.youtube.com##+js(set, yt.config_.EXPERIMENT_FLAGS.small_avatars_for_comments, false)
www.youtube.com##+js(set, yt.config_.EXPERIMENT_FLAGS.small_avatars_for_comments_ep, false)
```

**Comment by VampireChicken12** [comment]
@VictorJulianiR Do you still have the new UI?
I just read the following article that said YouTube reverted the new ui
https://9to5google.com/2024/04/25/youtube-redesign-reverted-backlash/

**Comment by VampireChicken12** [comment]
@VictorJulianiR I'm going to close this issue for now, Reopen it if the new UI comes back
