### ISSUE TITLE
Pause Background Players doesn't seem to work

### ISSUE THREAD

**Issue by slrgt** [YouTube-Enhancer/extension#441]
**Describe the bug**
Not sure if I'm doing something wrong but I have the Pause Background Players option enabled but if I start watching a different video the background players continue to play

**To Reproduce**

1. Start a video
2. Open a video in a new tab
3. Play the new tab's video

**Expected behavior**
The video in the background tab should pause

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Firefox
- Version 125

**Comment by VampireChicken12** [comment]
@livingflore can you look into this ?

**Comment by VampireChicken12** [comment]
@slrgt the fix for this bug is in version 1.24.2

**Comment by slrgt** [comment]
Awesome! Thank you!!
