### ISSUE TITLE
Buttons disappearing

### ISSUE THREAD

**Issue by Rewdyy** [YouTube-Enhancer/extension#460]
**Describe the bug**
The buttons (Loop, etc) disappear

**To Reproduce**

They are not present in some videos. It seems random

**Expected behavior**
The buttons should always be there

**Desktop (please complete the following information):**

Windows, chrome v 124.0.6367.118 (Build officiel) (64 bits)

**Comment by livingflore** [comment]
can't reproduce, what's the placement for buttons? can you attach some clip of it happening?

**Comment by VampireChicken12** [comment]
@stebo02 what version of the extension are you using.

**Comment by stebo02** [comment]
I just got the latest update! (2.0.125.1) The issue persists so that's why I came here.

**Comment by stebo02** [comment]
sorry i got the wrong github then ://

**Comment by VampireChicken12** [comment]
> sorry i got the wrong github then ://

It's fine.

**Comment by stebo02** [comment]
Should I delete my comments since they're unrelated?

**Comment by VampireChicken12** [comment]
> Should I delete my comments since they're unrelated?

No you can leave them. The person who originally made this issue maybe using enhancer for youtube as well. The names are similar but they are two different extensions my extension YouTube Enhancer is open source, the other extension named Enhancer for YouTube is closed source.

**Comment by VampireChicken12** [comment]
@Rewdyy what version of the extension are you using?
