### ISSUE TITLE
[Feature Request] (auto resolution): add fallback setting

### ISSUE THREAD

**Issue by Mabra51** [YouTube-Enhancer/extension#461]
**Is your feature request related to a problem? Please describe.**
Just a minor issue, but when using the auto resolution feature on videos that don't support the one you set, it defaults to the highest one available (usually 1080p, which takes ages to buffer).

**Describe the solution you'd like**
I think having a "fallback resolution" setting with the option of the closest available resolution (higher or lower) would be the best solution.
For example with 480p you would get 720p (closest higher) or 360p (closest lower)

**Comment by VampireChicken12** [comment]
@Mabra51 can you provide more information about how you want this fallback strategy to work. 

I was thinking about how I can implement this and came to the conclusion it isn't practical. If you select 480p and it isn't available the quality can only be lower. I've never seen a video have a quality level missing if it has higher quality it has the lower levels.

**Comment by VampireChicken12** [comment]
@Mabra51 How the automatic quality feature functions currently is as follows:
If the preferred quality is available it is applied if not the preferred quality is used to find the closest quality available on the video.

**Comment by Mabra51** [comment]
You mean it's already supposed to do that ?

I have it set to 480, but when a video doesn't have it it just goes to 1080, instead of 720 or 360.

**Comment by VampireChicken12** [comment]
> You mean it's already supposed to do that ?
> 
> I have it set to 480, but when a video doesn't have it it just goes to 1080, instead of 720 or 360.

Yes it is. Can you provide a link to a video so I can test this behavior.

**Comment by Mabra51** [comment]
Here's the most recent video i watched that lacks 480p.

https://youtu.be/9NgfV_KAV0s?si=VauPuGeNRWuuCtPt

**Comment by VampireChicken12** [comment]
@Mabra51 I will start to work on this tomorrow

**Comment by VampireChicken12** [comment]
I'm going to add a fallback mode that the user can configure the options will be higher and lower. If the desired resolution isn't available one lower or higher resolution will be picked based on the setting

**Comment by VampireChicken12** [comment]
@Mabra51 how does this look? Do you understand the meaning of the label and title
![Quality_Fallback_Strategy](https://github.com/YouTube-Enhancer/extension/assets/45531575/ca35fb5e-0556-4dc3-bebf-d8390d60da0f)

**Comment by Mabra51** [comment]
> @Mabra51 how does this look? Do you understand the meaning of the label and title ![Quality_Fallback_Strategy](https://private-user-images.githubusercontent.com/45531575/331901524-ca35fb5e-0556-4dc3-bebf-d8390d60da0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTA0NDIsIm5iZiI6MTcxNjE5MDE0MiwicGF0aCI6Ii80NTUzMTU3NS8zMzE5MDE1MjQtY2EzNWZiNWUtMDU1Ni00ZGMzLWJlYmYtZDgzOTBkNjBkYTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA3MjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZjY1NGEwYzY1ODk4MmQzMWE1NTAyNWY2OTQ4OTAzMTUxZGMwMjJjN2VlMWNlMmIyMjRkOWU1YjVjNzE0YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3n_1oHOW6v2OV9cJ6BvqIqX8QFKIJt2AOdAFAX0J5oo)

Yes, that's what i had in mind. 👍

**Comment by VampireChicken12** [comment]
> > @Mabra51 how does this look? Do you understand the meaning of the label and title ![Quality_Fallback_Strategy](https://private-user-images.githubusercontent.com/45531575/331901524-ca35fb5e-0556-4dc3-bebf-d8390d60da0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTA0NDIsIm5iZiI6MTcxNjE5MDE0MiwicGF0aCI6Ii80NTUzMTU3NS8zMzE5MDE1MjQtY2EzNWZiNWUtMDU1Ni00ZGMzLWJlYmYtZDgzOTBkNjBkYTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA3MjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZjY1NGEwYzY1ODk4MmQzMWE1NTAyNWY2OTQ4OTAzMTUxZGMwMjJjN2VlMWNlMmIyMjRkOWU1YjVjNzE0YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3n_1oHOW6v2OV9cJ6BvqIqX8QFKIJt2AOdAFAX0J5oo)
> 
> Yes, that's what i had in mind. 👍

Thanks for replying. I'll commit the code and merge it to dev branch later today.

**Comment by VampireChicken12** [comment]
@all-contributors please add @Mabra51 for ideas

**Comment by VampireChicken12** [comment]
@all-contributors please add @Mabra51 for ideas

**Comment by VampireChicken12** [comment]
@Mabra51 this feature has been released in version 1.26.0
