### ISSUE TITLE
[Feature Request] Remove `Translate to English` from the comments

### ISSUE THREAD

**Issue by G-Ran-Berg** [YouTube-Enhancer/extension#471]
It seems that YouTube offers translation for the comments and i can't find any disable button for it:
![image](https://github.com/YouTube-Enhancer/extension/assets/12037193/86062101-aed8-492d-82f2-701e5d786d91)

Is it possible to remove that annoying `Translate to English` (it is not only English language that will be shown here) with `YouTube Enhancer`?

If so, it would be really nice if you could make it possible to hide it with `YouTube Enhancer` 🤗

**Comment by VampireChicken12** [comment]
@G-Ran-Berg I can look into implementing such a feature

**Comment by VampireChicken12** [comment]
Alright I looked into implementing the feature, It should be easy to implement.

**Comment by taurusmaverick69** [comment]
Hi. Thanks for implementation. But "Translate to..." is still present in replies comments

**Comment by VampireChicken12** [comment]
> Hi. Thanks for implementation. But "Translate to..." is still present in replies comments

thank you for pointing this out. I will fix it soon

**Comment by VampireChicken12** [comment]
@taurusmaverick69 do you mind sending a link to a video that has reply comments that show "Translate to ..."

**Comment by taurusmaverick69** [comment]
https://www.youtube.com/watch?v=ujuoV_55Wt0

![image](https://github.com/user-attachments/assets/de558274-f327-4f58-a67f-b6ced734ab08)

**Comment by VampireChicken12** [comment]
@taurusmaverick69 thank you
