### ISSUE TITLE
[Feature Request] Skip back or ahead buttons.

### ISSUE THREAD

**Issue by vbmark** [YouTube-Enhancer/extension#486]
It would be handy if I could display two buttons "Below Player".

One that skips backwards 5 seconds and one that skips forwards 5 seconds.

Thank you very much!

**Comment by VampireChicken12** [comment]
Thanks for the suggestion again, I'll get to it as soon as possible.

**Comment by VampireChicken12** [comment]
@vbmark Do you think it would be a good idea to let the user customize how much the buttons go back and forward? I can do that when I implement the feature.

**Comment by vbmark** [comment]
Yes, it would be nice.  If I'm trying to understand some detail in a video, I may want to frequently go backwards in very small increments to get to just the right part.  However, if I just want an overview of something and am skipping around, then a larger increment setting is more useful.

**Comment by VampireChicken12** [comment]
> Yes, it would be nice. If I'm trying to understand some detail in a video, I may want to frequently go backwards in very small increments to get to just the right part. However, if I just want an overview of something and am skipping around, then a larger increment setting is more useful.

thank you for replying.

**Comment by VampireChicken12** [comment]
@vbmark the feature is almost done. I just need to fix a few issues related to the feature
![Rewind_By_Time](https://github.com/YouTube-Enhancer/extension/assets/45531575/484c85bc-40b5-47bd-80e1-f6d56aec814b)
![Fast_Forward_By_Time](https://github.com/YouTube-Enhancer/extension/assets/45531575/c1d631ef-1015-474d-bc45-eab50598c947)

**Comment by VampireChicken12** [comment]
@vbmark I'm still working on the feature, The functionality works but two of the button placement locations have the buttons out of order. I need to fix that then I will merge to dev branch and upload the extension built with the new feature. It will be a bit until it is released on the webstores. Thanks for your patience!

**Comment by VampireChicken12** [comment]
@vbmark thanks for your patience, until a new version of the extension is published I will attach the extension built here.

The version says 1.25.0 but it does have the new feature I just didn't update package.json

| File Name | SHA-256 Hash |
| :--- | :---: |
| [youtube-enhancer-v1.25.0-Chrome.zip](https://github.com/user-attachments/files/15888354/youtube-enhancer-v1.25.0-Chrome.zip | ce6f10b5080203f09f04ef8377702489ed097b37edd1995d61ff540bdfa20cb7 |
| [youtube-enhancer-v1.25.0-Edge.zip](https://github.com/user-attachments/files/15888374/youtube-enhancer-v1.25.0-Edge.zip) | ce6f10b5080203f09f04ef8377702489ed097b37edd1995d61ff540bdfa20cb7 |
| [youtube-enhancer-v1.25.0-Firefox.zip](https://github.com/user-attachments/files/15888379/youtube-enhancer-v1.25.0-Firefox.zip) | 71a83160e10e1b6e9a4c49ecb718a595ea2d6d092a41cb44565a87849c2f1f3d |

**Comment by vbmark** [comment]
When trying to install in Firefox, I get the message, "This addon could not be installed because it has not been verified".

I don't want to disable addon security so would it be possible for you to sign it?

**Comment by VampireChicken12** [comment]
> When trying to install in Firefox, I get the message, "This addon could not be installed because it has not been verified".
> 
> I don't want to disable addon security so would it be possible for you to sign it?

You have to load the extension has a temporary addon. This file isn't meant to be loaded as a normal extension

**Comment by VampireChicken12** [comment]
The extension will be signed when a new release is made and I uplpad the extension to the stores
