### ISSUE TITLE
[Bug Report] Extension fails to load

### ISSUE THREAD

**Issue by sergio-ezquerro-ochagavia** [YouTube-Enhancer/extension#497]
**Describe the bug**

After I downloaded the extension today from the Chrome Store, it seemed to work fine for a while, but after a certain point it just didn't even load most times I tried to watch a video.

Here's the text shown in the error, and a screenshot from the extension's errors tab (It appears multiple times, and I've only just enabled the option to save the errors):

`Uncaught (in promise) Error: Cannot access contents of the page. Extension manifest must request permission to access the respective host.`

![image](https://github.com/YouTube-Enhancer/extension/assets/111107240/e83f62c0-4b1e-4269-a189-1abdfb3b7294)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Vivaldi
- Version: 6.7.3329.31 (Stable channel) (64 bits)

**Additional context**

I have the following extensions enabled for youtube:

- 7TV (3.0.9) - ID: ammjkodgmmoknidbanneddgankgfejfh
- Ad Skipper (2.8.8) - ID: dinhbmppbaekibhlomcimjbhdhacoael
- ClearURLs (1.26.0) -ID: lckanjgmijmafbedllaakclkaicjfmnk
- Disconnect (20.3.1.1) - ID: jeoacafpbcihiomhlakheieifhpjdfeo
- Enhancer for YouTube™ (2.0.124.2) - ID: ponfpcnoihfmfllpaingbgckeeldkhle _**(This extension)**_
- LocalCDN (2.6.67) - ID: njdfdhgcmkocbgbhcioffdbicglldapd
- Return YouTube Dislike (3.0.0.16) - ID: gebbhagfogifgggkldgodflihgfeippi
- SponsorBlock dor YouTube (5.5.9) - ID: mnjggcdmjocbbbhaepdhchncahnbgone
- uBlock Origin (1.57.0) - ID: cjpalhdlnbpafiamejdnhcphjbkeiagm

More details: I have a Pi-Hole in my network as my dns, it pointing to the Quad9 (filtered, DNSSEC) DNS, and with the following adlists enabled. I don't think this should interfere with the extension, but it may help with the diagnosis:

- Default Pi-Hole List
- OISD Big List

**Comment by VampireChicken12** [comment]
@sergio-ezquerro-ochagavia thank you for your bug report. We will investigate the problem and see if we can produce the bug.

**Comment by sergio-ezquerro-ochagavia** [comment]
Weird, it began working properly now, after I disabled the extension in the settings. I'm not sure if it's an issue with the extension or with Vivaldi

Just to be clear, by disabling it I mean turning the toggle from the vivaldi://extensions/ page

![image](https://github.com/YouTube-Enhancer/extension/assets/111107240/8b4e2079-d4a6-4189-be27-05574f6cdf0b)

**Comment by VampireChicken12** [comment]
> Weird, it began working properly now, after I disabled the extension in the settings. I'm not sure if it's an issue with the extension or with Vivaldi
> 
> Just to be clear, by disabling it I mean turning the toggle from the vivaldi://extensions/ page
> 
> ![image](https://private-user-images.githubusercontent.com/111107240/332620740-8b4e2079-d4a6-4189-be27-05574f6cdf0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDAwMDIsIm5iZiI6MTcxNjMzOTcwMiwicGF0aCI6Ii8xMTExMDcyNDAvMzMyNjIwNzQwLThiNGUyMDc5LWQ0YTYtNDE4OS1iZTI3LTA1NTc0ZjZjZGYwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwMTAxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTM0OWZlZjMwZGRmZjZjY2M2NjlkMDdhYmQxYTg2ZjdiNGQ0YjQ4ZjVlMmIyZTNiMWM5MmM3NmFjZmViMjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J-06cXQpiQicXXzcvBnPWKqmbUC9QE0CpsStp5pcJew)

That is not my extension. I have no association with Enhancer for YouTube, when I started working on this extension I didn't even know it existed.

**Comment by sergio-ezquerro-ochagavia** [comment]
My bad, thanks for the correction
