### ISSUE TITLE
4.938 | Unwanted side panel automatically installed with each browser start

### ISSUE THREAD

**Issue by LinguaOccultus** [YouTube-Enhancer/extension#498]
**Describe the bug**
With one of the last versions the extension got a new function for showing its menu in a side panel (most likely the Chrome one). On Vivaldi (Chromium-based) and its much more advanced side or web panels, this install EACH time I start the browser even though this feature is disabled by default and I NEVER turned it on! Instead I just became aware of this new feature because of the side panels sudden appearance. Removing the side panel again, which I did many, MANY times now, does not work, as it just returns. The feature meanwhile is still disabled ... !?

The extension already has many, many other issues on Vivaldi as it seems and I am about to stop using it already. Maybe you could do some testing on this browser?

**To Reproduce**
Obvious:

1. Install Vivaldi
2. Install the extension
3. Restart the browser.

**Expected behavior**
Obvious: A disabled feature should not install itself automatically. And in the best case, the side panel should be removed again when the user disables it.

**Screenshots**
Not needed, I guess. Currently, even the unwanted side panel for the extension is just white. Something here is seriously broken!

**Desktop (please complete the following information):**

- OS: Windows 11 Pro 23H2
- Browser: Vivaldi, Desktop, Installed, 6.7.3329.35, Stable-Channel, Latest
- Version: 4.938 (Extension)

**Additional context**
I would like to see better support for this browser as there are SO many smaller issues with YouTube it is not funny anymore.

**Comment by VampireChicken12** [comment]
@LinguaOccultus wrong extension. This extension is not affiliated with Enhancer for YouTube.
