### ISSUE TITLE
[Bug Report] Maximize player feature broken

### ISSUE THREAD

**Issue by cryx0n** [YouTube-Enhancer/extension#505]
**Describe the bug**
New youtube layout broke the maximize function

**To Reproduce**
1. Go to youtube
2. Click maximize button
3. Nothing happens

**Expected behavior**
Clicking the button should maximize the video to fill the current browser tab

**Screenshots**
![youtube-enhancer-bug](https://github.com/YouTube-Enhancer/extension/assets/171316354/387c03aa-beb0-4cf2-9bf3-c60638d96cca)

**Desktop (please complete the following information):**

- OS: Windows 11
- Firefox
- Version 126.0.1 64bit

**Comment by VampireChicken12** [comment]
@cryx0n thanks for making this issue

**Comment by VampireChicken12** [comment]
@cryx0n I don't have the new layout so I can't really fix the issue.

**Comment by VampireChicken12** [comment]
@cryx0n this bug was fixed in 742be90 I will release a new version later today.

**Comment by cryx0n** [comment]
> @cryx0n this bug was fixed in [742be90](https://github.com/YouTube-Enhancer/extension/commit/742be90f71ad12de28deff895ec41e49025b2e0a) I will release a new version later today.

works perfectly on my end. awesome job!

**Comment by VampireChicken12** [comment]
> > @cryx0n this bug was fixed in [742be90](https://github.com/YouTube-Enhancer/extension/commit/742be90f71ad12de28deff895ec41e49025b2e0a) I will release a new version later today.
> 
> works perfectly on my end. awesome job!

that's excellent, Thanks!
