### ISSUE TITLE
YouTube Media Player Incorrect Size for the Default View

### ISSUE THREAD

**Issue by monkeyzone456** [YouTube-Enhancer/extension#513]
**Describe the bug**
YouTube Player and video Incorrect size. Seems to be using theater mode sizes for default view. In doing so almost all player controls are inaccessible and scrub preview is lost

**To Reproduce**

1. Update to newest chreome extension version
2. Play Video on default view

**Expected behavior**
Not a broken media player

**Screenshots**
![Screenshot 2024-06-07 170256](https://github.com/YouTube-Enhancer/extension/assets/67808013/8a501253-0b32-4d02-9d87-2a92aafeb464)
**Desktop (please complete the following information):**

- OS: W10
- Browser: Chrome
- Version: 2.0.125

**Additional context**

**Comment by monkeyzone456** [comment]
Not necessarily apart of the bug report itself but in theater and fullscreen it works perfectly fine

**Comment by VampireChicken12** [comment]
I think you maybe using another extension that isn't related to this one. This extension doesn't have a version 2.0.125
