### ISSUE TITLE
[Feature Request] Hide "includes paid promotion" banner

### ISSUE THREAD

**Issue by rado84-github** [YouTube-Enhancer/extension#519]
Can you make an option which would hide the "includes paid promotion" banner on videos? This extension: https://addons.mozilla.org/bg/firefox/addon/youtube-paid-promotion-hider/ does that but I know from experience that having a few extensions for youtube inevitably leads to errors at some point.

**Comment by VampireChicken12** [comment]
@rado84-github I should be able to do that.

**Comment by VampireChicken12** [comment]
@rado84-github this feature has been released in version 1.26.0

**Comment by Styphoryte** [comment]
Can you please hide them as well from inside the thumbnail previews whenever this option is enabled please? I have an unnecessary  extension I use just to hide these promotional banners from the thumbnails + videos but if you are able to hide them from the Preview thumbnails I would definitely just uninstall that one and use yours so I don't need all these YouTube extensions lmao. Appreciate the extension, and thanks for all your work!!
