### ISSUE TITLE
[Feature Request] Show total length of a playlist in sidebar

### ISSUE THREAD

**Issue by at-pyrix** [YouTube-Enhancer/extension#542]
**Is your feature request related to a problem? Please describe.**
Sometimes, while watching a long YouTube playlist, I need to know the total length. This is very useful for students and people watching a course on a subject through YT in estimating the time required.

**Describe the solution you'd like**
A total duration of the playlist on the sidebar would do the trick.

It would be even better if it reacted to the playback speed, just like the remaining time does. For example, if I'm watching the current video at 2x speed, the playlist length should change to 5h:15h:18s.

![image](https://github.com/YouTube-Enhancer/extension/assets/90166733/1a05ff96-6c68-4eb5-8e2e-5f80be6ae171)

**Describe alternatives you've considered**
Using the following website: https://ytplaylist-len.sharats.dev/ (maybe some code can be used [from here](https://github.com/sharatsachin/ytplaylist-len) to make it easier?)

**Comment by VampireChicken12** [comment]
thanks for the suggestion @at-pyrix I had this idea almost 4 months ago I just never looked into it much more than I did then.

![image](https://github.com/YouTube-Enhancer/extension/assets/45531575/2632e34b-7d34-48b4-a89c-c6ce1d340f04)

**Comment by VampireChicken12** [comment]
I planned on making the displayed time match the style that shows when looking at a video's length. I could do it how you showed in your screenshot it wouldn't be much more work.

**Comment by VampireChicken12** [comment]
This feature will require a [YouTube Data v3 API key](https://developers.google.com/youtube/registering_an_application) I think we should be able to include one in the extension but also have the option to use your own key it is possible the included key could be rate limited

**Comment by VampireChicken12** [comment]
Making the  feature react to the video speed shouldn't be hard at all

**Comment by at-pyrix** [comment]
Amazing! Thank you for your time.

**Comment by VampireChicken12** [comment]
> Amazing! Thank you for your time.

you're welcome

**Comment by at-pyrix** [comment]
Also, can we have something like this?

![image](https://github.com/YouTube-Enhancer/extension/assets/90166733/a335d4c7-00e0-4f4a-845f-7f2598411c35)

<p align=center><i><a href="https://chromewebstore.google.com/detail/youtube-playlist-duration/klbacnllhiilbiiedcbgfafmnedldgeg">
YouTube Playlist Duration bar</a></i></p>

**Comment by VampireChicken12** [comment]
> Also, can we have something like this?
> 
> ![image](https://private-user-images.githubusercontent.com/90166733/345999127-a335d4c7-00e0-4f4a-845f-7f2598411c35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTMzMzAsIm5iZiI6MTcyMDE1MzAzMCwicGF0aCI6Ii85MDE2NjczMy8zNDU5OTkxMjctYTMzNWQ0YzctMDBlMC00ZjRhLTg0NWYtN2YyNTk4NDExYzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA0MTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NjMzOTM2M2I1Yjk2OTJlZTg5ZTlmMjBjYmI1OWNiOTg4MzliMDgzYzczZDA5NThiNjExMmU1MGVkM2RjMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-DJ2-FFUaHnLS2C0xwTtx5HfCEvPqKd00vF-ZN9y3Hc)
> 
> [ YouTube Playlist Duration bar](https://chromewebstore.google.com/detail/youtube-playlist-duration/klbacnllhiilbiiedcbgfafmnedldgeg)

I can look into doing that. I currently don't know how to get the amount watched of the videos in the playlist for the user.

**Comment by at-pyrix** [comment]
Wait I just found out that this extension is on gh: https://github.com/WaiShen1000/YouTube-Playlist-Duration-bar

**Comment by VampireChicken12** [comment]
> Wait I just found out that this extension is on gh: https://github.com/WaiShen1000/YouTube-Playlist-Duration-bar

oh nice

**Comment by at-pyrix** [comment]
Leave it, that would just increase your workload when there's already an extension for that. my main concern was that it wasn't open-source but now I found out it is, so no problem with that.

**Comment by VampireChicken12** [comment]
I see no api is used with this extension. It must be limited to the amount of videos you load from the playlist part

**Comment by at-pyrix** [comment]
yeah

**Comment by at-pyrix** [comment]
Are you interested in implementing this feature? because now it seems unnecessary, as there is already an extension for it. It doesn't react to playback speeds though, although that is just a minor inconvenience.

**Comment by VampireChicken12** [comment]
> Are you interested in implementing this feature? because now it seems unnecessary, as there is already an extension for it. It doesn't react to playback speeds though, although that is just a minor inconvenience.

Yes I am

**Comment by at-pyrix** [comment]
Oh okay, then :) Thanks :+1:

**Comment by VampireChicken12** [comment]
> Oh okay, then :) Thanks 👍

no problem.

**Comment by VampireChicken12** [comment]
that extension is limited to the amount of videos you load in the playlist side element. If a playlist is big enough it will show 200 videos then you have to go to the last video to load more.

**Comment by VampireChicken12** [comment]
@at-pyrix do you know about the discord server for the extension? If you use discord feel free to join and discuss this suggestion and others you might have.

**Comment by VampireChicken12** [comment]
Here's the invite link [YouTube Enhancer Extension Discord Server](https://discord.com/invite/VpdGFmuB4B)

**Comment by at-pyrix** [comment]
I'm sorry but I don't use discord.

**Comment by VampireChicken12** [comment]
> I'm sorry but I don't use discord.

That's fine

**Comment by VampireChicken12** [comment]
@at-pyrix I started working on this feature. I'm thinking of a way to handle fetching the playlist info and each videos duration without destroying the API thus hitting quota limit fast

**Comment by at-pyrix** [comment]
Have you tried looking into the extension's source code I sent you earlier?

**Comment by VampireChicken12** [comment]
> Have you tried looking into the extension's source code I sent you earlier?

the extension that shows the progress of the playlist and the total length 
If that is what you are talking about then yes. I have determined that code isn't useful, it doesn't use the api so it is limited to the amount of videos you have currently loaded on the side of the playlist menu.

**Comment by VampireChicken12** [comment]
Showing the progress could be possible but it will be limited to the amount of videos loaded.

**Comment by at-pyrix** [comment]
I see

**Comment by VampireChicken12** [comment]
I noticed the author of this extension mentions the length of the playlist only considers what is shown
https://github.com/WaiShen1000/YouTube-Playlist-Duration-bar/blob/main/scripts/duration-playing.js#L44

**Comment by VampireChicken12** [comment]
When analyzing the code for the extension you linked. I realized it is very rudimentary it assumes you watched all videos that occur before it fines the current video you are watching. In my code I'm getting the progress from the thumbnail shown with the red filled progress bar.

**Comment by VampireChicken12** [comment]
more progress d28d19f9603e5cc033ce35324bbbc9958c615864

**Comment by VampireChicken12** [comment]
![(146)_Minecraft_Create_Arcane_Engineering_Ep _1_-__1rdhTkTOds](https://github.com/YouTube-Enhancer/extension/assets/45531575/a8621de1-c1e1-4a2a-a7e6-1ad652decadb)
this design may not be final but what do you think of it @at-pyrix

**Comment by at-pyrix** [comment]
Yeah it's pretty good!

As for the design, I think the background color is a bit too bright. Also, let's change the 79h22m14s to 79:22:14. And I think increasing the padding a bit would help.

Here's what I have in mind:

![image](https://github.com/YouTube-Enhancer/extension/assets/90166733/7bd1a928-117b-4c24-a217-88976a29554b)

**Comment by VampireChicken12** [comment]
> Yeah it's pretty good!
> 
> As for the design, I think the background color is a bit too bright. Also, let's change the 79h22m14s to 79:22:14. And I think increasing the padding a bit would help.
> 
> Here's what I have in mind:
> 
> ![image](https://private-user-images.githubusercontent.com/90166733/346495934-7bd1a928-117b-4c24-a217-88976a29554b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjk0NjYsIm5iZiI6MTcyMDQyOTE2NiwicGF0aCI6Ii85MDE2NjczMy8zNDY0OTU5MzQtN2JkMWE5MjgtMTE3Yi00YzI0LWEyMTctODg5NzZhMjk1NTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA4NTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDRmNGZlZmE4N2FjMWY1ZWJiZjBlYjNiNGU2YjAyYmFlMjQ4ZjgyN2RiNjFkZDAzZjNiYmY2ZmU5NGE1NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UmN6llAXklp8eezqp-tTmQrcsGvNHHNNXHNc8wTuCcE)

thanks for the input. I intended to match the design of youtube but I can do this.

**Comment by VampireChicken12** [comment]
@at-pyrix can you provide the border radius and the height of the progress bar? and the percentage part

**Comment by VampireChicken12** [comment]
@at-pyrix how does this look
![(148)_Minecraft_Create_Arcane_Engineering_Ep _2_-__AYzK1MVPs6](https://github.com/YouTube-Enhancer/extension/assets/45531575/8a74e13c-c83f-4a08-aef3-3748ff610627)

**Comment by at-pyrix** [comment]
Wow! That looks amazing! Great job

**Comment by VampireChicken12** [comment]
> Wow! That looks amazing! Great job

thanks

**Comment by at-pyrix** [comment]
hey btw, is is dynamic i.e., does it instantly change the progress with respect to the video? Because the original extension doesn't do this. It only changed the length once you switch to a different video.

**Comment by VampireChicken12** [comment]
> hey btw, is is dynamic i.e., does it instantly change the progress with respect to the video? Because the original extension doesn't do this. It only changes the length once you switch to a different video.

not right now but I do plan on doing that. 
https://github.com/YouTube-Enhancer/extension/commit/88e2fddca83476270191a3bf83fb534ea183e9d9#diff-fcd6cce9790db1826feed58f12c66d972e852afc2f8034b38b4ff4fd08551a11L54

**Comment by VampireChicken12** [comment]
the feature isn't 100% finished I still need to do some of the coding for the logic and also add the setting for the YouTube Data API V3 key and enabling this feature itself

**Comment by at-pyrix** [comment]
Hmm, I understand. Good luck!

**Comment by VampireChicken12** [comment]
@at-pyrix thanks for the star
@all-contributors please add @at-pyrix for ideas

**Comment by VampireChicken12** [comment]
no problem

**Comment by VampireChicken12** [comment]
https://github.com/YouTube-Enhancer/extension/assets/45531575/3ab4963e-ba51-4ee2-852e-e04aa08b0697

@at-pyrix here is a demo of the live updating progress

**Comment by at-pyrix** [comment]
pretty cool

**Comment by at-pyrix** [comment]
hey, is the progress bar working correctly though? I can see it's the second video out of 56, and the progress bar is more than half complete.

**Comment by VampireChicken12** [comment]
> hey, is the progress bar working correctly though? I can see it's the second video out of 56, and the progress bar is more than half complete.

yes it is, I'm testing with a playlist I almost finished in the past

**Comment by VampireChicken12** [comment]
the extension you linked doesn't calculate the progress like that, Like I said it just assumes everything before the currently playing video is watched

**Comment by VampireChicken12** [comment]
I could modify the code to only count the videos before the current video then add on the current time of that video but then the watched time wouldn't be as reliable because instead of going based on what YouTube tracked as watched the could would just add the full length of the video.

**Comment by VampireChicken12** [comment]
> > I could modify the code to only count the videos before the current video then add on the current time of that video but then the watched time wouldn't be as reliable because instead of going based on what YouTube tracked as watched the code would just add the full length of the video.
> 
> yeah that's probably a better decision

keeping it how it is or changing it?

**Comment by at-pyrix** [comment]
changing it

**Comment by VampireChicken12** [comment]
alright

**Comment by VampireChicken12** [comment]
What do you think of this: 
I can change the code to only count videos before the current video and the progress of the current video but instead of adding the full length do what the code currently does and adds what youtube tracked. 

I just thought I'd put it out there I can do it the aforementioned way.

**Comment by at-pyrix** [comment]
> adds what youtube tracked.
wdym?

**Comment by VampireChicken12** [comment]
> > adds what youtube tracked.
> 
> wdym?

I meant `add what youtube tracked` but I'll explain. YouTube keeps track of your progress watching videos. The current code uses the data from the progress bar that youtube puts on the thumbnail to determine how much is watched.

**Comment by at-pyrix** [comment]
nah, I think that would quickly complicate things. I think sticking to the previous approach would be better

OR

you could give the users a toggle, whether to use method 1 or 2. what do you think?

**Comment by VampireChicken12** [comment]
The only thing that will complicate things is doing it the other way.

I could add a toggle but I'd have to come up with a good way to explain what each option does

**Comment by at-pyrix** [comment]
but if we use the youtube tracked length, then it wouldn't react to the video, which is not what we want.

I think a simple toggle could work.

- [x] **Show playlist progress**
  - [ ] Use YouTube's API to get tracked progress. ℹ️

hovering over the ℹ️ button would give a detailed explanation.


Or we could make a compromise, use YouTube's tracked length for other videos, but for the current video, make the length reactive.

**Comment by VampireChicken12** [comment]
> but if we use the youtube tracked length, then it wouldn't react to the video, which is not what we want.
> 
> I think a simple toggle could work.
> 
> * [x]  **Show playlist progress**
>   
>   * [ ]  Use YouTube's API to get tracked progress. ℹ️
> 
> hovering over the ℹ️ button would give a detailed explanation.
> 
> Or we could make a compromise, use YouTube's tracked length for other videos, but for the current video, make the length reactive.

it would react to the current video

**Comment by VampireChicken12** [comment]
yeah I can do that.

**Comment by at-pyrix** [comment]
> > but if we use the youtube tracked length, then it wouldn't react to the video, which is not what we want.
> > I think a simple toggle could work.
> > 
> > * [x]   **Show playlist progress**
> >   
> >   * [ ]   Use YouTube's API to get tracked progress. ℹ️
> > 
> > hovering over the ℹ️ button would give a detailed explanation.
> > Or we could make a compromise, use YouTube's tracked length for other videos, but for the current video, make the length reactive.
> 
> it would react to the current video

Well, then I've got no issues 🙌

**Comment by VampireChicken12** [comment]
@at-pyrix I'm going to add a fallback logic in the code if the api limit is hit the code will use the pages list of videos to get the total length of the video. Right now how the code is setup is as follows:
1. get the playlist from the api with list of all video ids
2. get duration for each of those video ids

The watched time can't be got from the api because that doesn't exist.

It will be limited to the amount of videos showing in the playlist side panel but it's better than the feature not working at all. Some people may not be savy enough to get their own api key and even then the qouta could easily be hit on their key.

**Comment by VampireChicken12** [comment]
I'm still working on this. It will probably take a couple days. I'd rather get it nearly perfect instead of releasing quick with bugs. Of which there are a few I need to fix.

**Comment by VampireChicken12** [comment]
@all-contributors please add @at-pyrix for design

**Comment by VampireChicken12** [comment]
I added you for design since you inspired the design of the playlist length display

**Comment by VampireChicken12** [comment]
![YouTube_Enhancer__Options_-_Google_Chrome_WG376ZzYDY](https://github.com/YouTube-Enhancer/extension/assets/45531575/28dab438-440e-4f31-9ee6-aece6a4aeea5)
I just finished the settings stuff for the feature

**Comment by at-pyrix** [comment]
Amazing!

**Comment by at-pyrix** [comment]
so, is the feature complete now?

**Comment by VampireChicken12** [comment]
> so, is the feature complete now?

@at-pyrix no it's still has a good amount of code to be made.

**Comment by VampireChicken12** [comment]
I need to re-write the code to enable the feature to get the playlist length based on the get method (API, HTML) then I need to test it all and add some mutation observers to update the playlist info on changes

**Comment by VampireChicken12** [comment]
Also there are many different kinds of playlist some of those types I can't get the length info with the API so I need to account for those. @at-pyrix

**Comment by at-pyrix** [comment]
You mean private playlists, Watch Later and Liked Videos?

**Comment by VampireChicken12** [comment]
> You mean private playlists, Watch Later and Liked Videos?

yes and mixes and others.

**Comment by at-pyrix** [comment]
Hey, any updates?

**Comment by VampireChicken12** [comment]
> Hey, any updates?

no I haven't worked on the code in a couple days.

**Comment by VampireChicken12** [comment]
Update including but not limited to
// TODO: handle intelligent caching of response so the quota is hit as fast
// TODO: Implement playlist length fallback when api hits quota or errors

**Comment by VampireChicken12** [comment]
The fallback method has been implemented. Now I will try to come up with a caching method for the API, I might make the fallback be what happens if the limit is hit. I need to test more and make sure it's working fine in different scenarios. @at-pyrix

**Comment by VampireChicken12** [comment]
two more things among others that I might discovered need fixing
when navigating from a video to a mix playlist the total length doesn't display as the right time
Update the length ui when the page of type "playlist" is scrolled to load more videos

**Comment by VampireChicken12** [comment]
Still working on this. I found a few more minor issues I need to fix.

**Comment by VampireChicken12** [comment]
I haven't worked on the code in a couple days. It will be finished eventually. Thanks for your patience @at-pyrix

**Comment by at-pyrix** [comment]
any progress?

**Comment by VampireChicken12** [comment]
> any progress?

@at-pyrix no sorry I've been busy.

**Comment by VampireChicken12** [comment]
a little progress was made in the most recent commit. I still need to try to handle caching or something like that. How the code is currently will make the api rate limit happen quite fast.

**Comment by VampireChicken12** [comment]
@at-pyrix I just need to test a few more things and finish a thing or two then I think the feature should be done.

**Comment by at-pyrix** [comment]
Great!

**Comment by VampireChicken12** [comment]
## Release Artifacts
| File Name | SHA-256 Hash |
| :--- | :---: |
| [youtube-enhancer-v1.27.0.0-Chrome.zip](https://github.com/user-attachments/files/16407521/youtube-enhancer-v1.27.0.0-Chrome.zip) | fcb39152c33daf35bec4e06205cb5c15c8bfede482eebe06ded8d1c8fbe9dca7 |
| [youtube-enhancer-v1.27.0.0-Edge.zip](https://github.com/user-attachments/files/16407523/youtube-enhancer-v1.27.0.0-Edge.zip) | fcb39152c33daf35bec4e06205cb5c15c8bfede482eebe06ded8d1c8fbe9dca7 |
| [youtube-enhancer-v1.27.0.0-Firefox.zip](https://github.com/user-attachments/files/16407526/youtube-enhancer-v1.27.0.0-Firefox.zip) | 0fe56591f360e51a83317000495ad8d40b5fb823c6c9020e54e3f9026f553d44 |

@at-pyrix these aren't signed you will have to load as unpacked or temporary extension if you want to use the feature before it is released. I like to release a couple fixes or features before making a new release on the webstores.

**Comment by VampireChicken12** [comment]
the version number is followed by an extra 0 to indicate a pre-release version. Extensions don't allow appending -prerelease after the version number

**Comment by at-pyrix** [comment]
thanks

**Comment by VampireChicken12** [comment]
@at-pyrix you're welcome, if you find any bugs or anything you think is an issue make an issue about it please and thank you.

**Comment by at-pyrix** [comment]
Alright! (I think we should end this with 100 comments lol)

**Comment by at-pyrix** [comment]
Also, when are you gonna release this (pre-built)?

**Comment by VampireChicken12** [comment]
Not sure it might be a couple days or a week or weeks it depends on when I get more done.

**Comment by at-pyrix** [comment]
Fair enough.

**Comment by at-pyrix** [comment]
Hey how do I install this?

I followed the README and did the following:
```sh
git clone https://github.com/YouTube-Enhancer.git
cd youtube-enhancer
npm install
npm run build
```

at first, the dist folder was empty. so i went in and changed the `vite.config.ts`
```diff
		build: {
			emptyOutDir: false,
			modulePreload: false,
-                       outDir: resolve(outDir, "temp"),
+			outDir: 'dist',
```

then I imported the dist folder into chrome (brave) and got the following error

```
Manifest file is missing or unreadable
Could not load manifest.
```

**Comment by at-pyrix** [comment]
Hey, what do you think of this?

![image](https://github.com/user-attachments/assets/ce97984a-a4ca-4697-ae31-7a23927c990d)
![image](https://github.com/user-attachments/assets/2edf7b61-d54c-4df5-a597-567891910247)


It's using the `--yt-lightsource-section2-color` variable for the background color.

**Comment by VampireChicken12** [comment]
I should be able to apply that change.

**Comment by VampireChicken12** [comment]
> Also, when are you gonna release this (pre-built)?
@at-pyrix i attached the extension pre built in a comment. You just need to extract the zip and select the folder

**Comment by at-pyrix** [comment]
> > Also, when are you gonna release this (pre-built)?
> > @at-pyrix i attached the extension pre built in a comment. You just need to extract the zip and select the folder
sorry, I didn't see that at the time

**Comment by VampireChicken12** [comment]
> sorry, I didn't see that at the time
No problem

**Comment by VampireChicken12** [comment]
@at-pyrix is the feature working alright so far?

**Comment by at-pyrix** [comment]
> @at-pyrix is the feature working alright so far?

It is. Btw, how was the `HTML` option supposed to work? Does it include all the videos before the one you've watched? Because that's a bit more handy, specially if you don't keep a YouTube history or simply completed half of the playlist with another account and now want to continue.

**Comment by VampireChicken12** [comment]
> > @at-pyrix is the feature working alright so far?

> It is. Btw, how was the `HTML` option supposed to work? Does it include all the videos before the one you've watched? Because that's a bit more handy, specially if you don't keep a YouTube history or simply completed half of the playlist with another account and now want to continue.

Yes it includes the ones before you watched but only the amount tracked on that account. The feature doesn't assume you watched it all.

**Comment by VampireChicken12** [comment]
The html option uses the pages data to get the playlist duration and the playlist watch time. it is not possible to get the watch time from the api. so the api type uses the api to get the playlist duration and the page data for the watch time

**Comment by VampireChicken12** [comment]
if needed I could modify the code to assume you watched any videos prior to the one you are on. I could add a checkbox for that or something

**Comment by at-pyrix** [comment]
Good idea

**Comment by VampireChicken12** [comment]
> Good idea

I thought about it a bit. I think I'd need to think of the right way to word the checkbox label/title.

**Comment by VampireChicken12** [comment]
@at-pyrix 
![Method_To_Get_Watched_Time](https://github.com/user-attachments/assets/592475ae-3dff-4340-be9d-2c59acc5d8c0)
how is this?

**Comment by VampireChicken12** [comment]
> Hey, what do you think of this?
> 
> ![image](https://private-user-images.githubusercontent.com/90166733/352975545-ce97984a-a4ca-4697-ae31-7a23927c990d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODQzNTAsIm5iZiI6MTcyMjQ4NDA1MCwicGF0aCI6Ii85MDE2NjczMy8zNTI5NzU1NDUtY2U5Nzk4NGEtYTRjYS00Njk3LWFlMzEtN2EyMzkyN2M5OTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAzNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NmM0NGY0OTFjNzA3M2Q2MGYyZWI1NjIyMGU2NDc4MzllMzc2MDI3ODE5OWJkODlhODU1ZDVjMWUxMGMzMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.brXtzdE7auSxmpIdbRIYTQWiFu8ynGk2e05pw8Gc1C8) ![image](https://private-user-images.githubusercontent.com/90166733/352976999-2edf7b61-d54c-4df5-a597-567891910247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODQzNTAsIm5iZiI6MTcyMjQ4NDA1MCwicGF0aCI6Ii85MDE2NjczMy8zNTI5NzY5OTktMmVkZjdiNjEtZDU0Yy00ZGY1LWE1OTctNTY3ODkxOTEwMjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAzNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZmUwNzBkMjY0YjI4MzdhNmZlZGYwNTgxNTJiZDFhMjRjNGVhM2RmMmNkYzExZDI0Y2YxZGM2YjNkNDQ4M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uRB6da7RQktBM5uvInpTnRT0Lt0p_BOqmFOx2Q1Mx1I)
> 
> It's using the `--yt-lightsource-section2-color` variable for the background color.

Where does that selector get modified? is it just something that changes automatically

**Comment by VampireChicken12** [comment]
@at-pyrix I've attached the extension pre-built with the new select for how watch time is obtained.
## Release Artifacts
| File Name | SHA-256 Hash |
| :--- | :---: |
| [youtube-enhancer-v1.27.0.1-Chrome.zip](https://github.com/user-attachments/files/16450782/youtube-enhancer-v1.27.0.1-Chrome.zip) | 12db435f44b308ec79be32b365064c383ae959fc728046a2ea5ff628635aed78 |
| [youtube-enhancer-v1.27.0.1-Edge.zip](https://github.com/user-attachments/files/16450783/youtube-enhancer-v1.27.0.1-Edge.zip) | cd9803ad61979c65d8b25bc3839cb2247f729f9f5e739ff85eb765d188842d1b |
| [youtube-enhancer-v1.27.0.1-Firefox.zip](https://github.com/user-attachments/files/16450789/youtube-enhancer-v1.27.0.1-Firefox.zip) | 0e8db7f16a81cfb1887f7a260556458b2268e479ece95d05b37e817060e9742e |

**Comment by VampireChicken12** [comment]
@at-pyrix is everything still working fine with the feature? have you found any bugs or is there anything you want changed

**Comment by at-pyrix** [comment]
It's working perfectly fine :)

**Comment by at-pyrix** [comment]
thanks

**Comment by VampireChicken12** [comment]
@at-pyrix great to hear thanks for replying
