### ISSUE TITLE
[Bug Report] "Hide end screen cards" doesn't seem to be working anymore

### ISSUE THREAD

**Issue by rado84-github** [YouTube-Enhancer/extension#561]
**Describe the bug**
At the end of a video I still see those "cards" that are like visual links to other videos. See the attached screenshot.

**To Reproduce**

1. Open any video (the option to hide end screen cards must be enabled), like this one of instance: https://www.youtube.com/watch?v=o1tj2zJ2Wvg 
2. Skip to the 4th minute and wait for the end of the video.
3. Observe those cards appearing.

**Expected behavior**
Those cards shouldn't appear, the video must be clean of any additional elements.

**Screenshots**
![Picture_created_27-07-2024_22-04-01](https://github.com/user-attachments/assets/7191a8d3-40c3-4ada-a1bd-4ef0d1a74a10)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: Firefox 128.0.3
- Version: 1.26.0

**Comment by VampireChicken12** [comment]
@rado84-github maybe it's a browser issue. it works fine for me.

**Comment by VampireChicken12** [comment]
I tried with firefox version 128.0 and it works fine

**Comment by rado84-github** [comment]
It IS a bug alright, I'm just not sure whose bug. Aside from here, earlier I asked on a forum whether they have similar problems with other extensions and they said this sometimes happens to extension that have the setting about restricted sites. The user has to allow running on restricted sites, protected by Mozilla, close the browser, delete cache, open the site with the problem and do Ctrl+F5 - in that specific order. YTE has that setting:

![Picture_created_27-07-2024_23-46-10](https://github.com/user-attachments/assets/88198ba1-8582-44cf-b023-4ebcb2b5a426)

So I'm guessing this bug is a combination of Firefox + extension permissions + security updates of Firefox. IDK whether you receive those in Spyware 11 but in Linux updates to Firefox that end with .1, .2, .3 and so on are security updates. Mine's 128.0.3.

I'll know it for the next time/next extension and you can delete this bug report, if you want.
