### ISSUE TITLE
"Embed" version overlaps AddOn

### ISSUE THREAD

**Issue by SirClaver** [YouTube-Enhancer/extension#578]
**Describe the bug**
Since a few weeks the AddOn isn't working properly anymore on Firefox. When the page (video) is loading it stops, reloads again and puts an "embed" video before the actual enhancer version of the video just like you loaded a embed version on X or reddit or something. Sometimes the video starts twice at the same time and you have overlayed sounds. You won't have shortcuts anymore and previews on the "main site" won't work either. Very rarely the enhancer loads but if you press play or the shortcut it stays "stuck" on the video.

**To Reproduce**

1. Go to any video, it doesn't work anymore at all

**Expected behavior**
Well, it was fine several years before. It suddenly stopped working even after the last update in June.

**Screenshots**
Screenshots won't help as it looks like regular enhancer YT and if not it looks like an embed version where you can press the "watch on YT" button.

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 22H2
- Firefox 
- latest update

**Additional context**
I tried deleting and reinstalling both the AddOn and the whole browser and cookies and cache. Nothing seems to work and I really don't want to change my browser.

**Comment by VampireChicken12** [comment]
@SirClaver can you tell me the extension version you are on

**Comment by VampireChicken12** [comment]
@SirClaver you aren't using my extension you are using Enhancer for YouTube. I can't help the latest version of this extension is 1.26.0

**Comment by SirClaver** [comment]
I'm so sorry I was sure I'm on the github for the right extension. but now I'll be testing your enhancer. nice.

**Comment by VampireChicken12** [comment]
It's fine people mix it up a lot

**Comment by VampireChicken12** [comment]
@SirClaver my extension isn't quite as full featured as the other but I am willing to add more features
