### ISSUE TITLE
Shadow under numbers on video when changing speed

### ISSUE THREAD

**Issue by slrgt** [YouTube-Enhancer/extension#591]
**Is your feature request related to a problem? Please describe.**
When changing the speed of the video its sometimes impossible to see the number on the video because the video is also white or a very light color.

**Describe the solution you'd like**
If there was a bit of shadow under the numbers it would make it legible regardless of what color is on the video

**Comment by VampireChicken12** [comment]
@slrgt can you attach a screenshot that highlights this issue with visibility

**Comment by slrgt** [comment]
sorry about that, here are screenshots

![floorp_mgyIXqMi5V](https://github.com/user-attachments/assets/0ada98c5-4cef-41ad-aa8a-05267f1a859f)

![floorp_nfjshfL2J5](https://github.com/user-attachments/assets/420ada97-e4f8-4e4c-89cb-62262bdd0590)

**Comment by VampireChicken12** [comment]
okay let me look into adding a shadow or maybe a thin outline
