### ISSUE TITLE
[Feature request] Not show music videos on home page

### ISSUE THREAD

**Issue by G-Ran-Berg** [YouTube-Enhancer/extension#608]
I'm not interested in music videos and would like to have these videos hidden or removed:

![image](https://github.com/user-attachments/assets/db1b8503-b325-43f6-a3ad-a4177568c1bd)

As you can see on the picture the music video seems to have the sign `♪` and maybe it is possible to use that when hiding the videos or if you can find a better way to detect them you are free to do so. 😊

I understand it will not hide all music videos, but at least those that are `Official Artist Channel`.

**Comment by VampireChicken12** [comment]
@G-Ran-Berg I will look into it

**Comment by VampireChicken12** [comment]
@G-Ran-Berg do you want this feature to just work on the home page ? or would you like the feature to hide official artist videos in general

**Comment by VampireChicken12** [comment]
I can easily do both if that is something you want @G-Ran-Berg

**Comment by VampireChicken12** [comment]
Right now the feature only hides the home page official artist videos I can modify it to hide all
7e202f1d1108df515c9897c44a9b493784b9b4ef

**Comment by VampireChicken12** [comment]
@G-Ran-Berg it's been a bit since I mentioned you can you share your input on this.

Do you want the feature to remove all official artist videos from all places they can appear or just the home page

**Comment by VampireChicken12** [comment]
@G-Ran-Berg I would like your input on whether or not you think removing official artist videos from all of YouTube is something you'd like

**Comment by VampireChicken12** [comment]
@G-Ran-Berg this feature has been released in version 1.27.0 I can modify the feature to hide official artist videos everywhere if you would like that.
