### ISSUE TITLE
Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.

### ISSUE THREAD

**Issue by codehz** [YouTube-Enhancer/extension#621]
**Describe the bug**
There are some suspicious errors in the developer tools

**To Reproduce**

0. In Chrome/Chromium-based browser
1. Open DevTools

Unhandled rejection: TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.

**Expected behavior**
I don't think it is normal behavior, but I can't know what is broken...

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser [e.g. chrome, safari] Arc (Chromium Engine Version 129.0.6668.59)

**Additional context**
Seems related to https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API 
I think it is possible to just bypass those like this userscript: https://greasyfork.org/zh-CN/scripts/433051-trusted-types-helper/code

**Comment by VampireChicken12** [comment]
@codehz Thank you for reporting the issue. I have known about this for a while it has to do with the hide scrollbar feature. I'm going to fix it eventually.
