### ISSUE TITLE
[Feature Request] Remove speed limit

### ISSUE THREAD

**Issue by ShawkMusic** [YouTube-Enhancer/extension#637]
Don't add arbitrary restrictions for no reason. Let me set the video's speed to whatever I want.

**Comment by VampireChicken12** [comment]
@ShawkMusic it isn't an arbitrary restriction although it is lower than the max. The maximum speed the video element can be set to is 16x I could definitely increase the limit to this.

**Comment by ShawkMusic** [comment]
> @ShawkMusic it isn't an arbitrary restriction although it is lower than the max. The maximum speed the video element can be set to is 16x I could definitely increase the limit to this.

That sounds good. I made a pull request.

**Comment by VampireChicken12** [comment]
@ShawkMusic Increased the speed limit on the dev branch. This feature might not be released for a while I'm not sure.

**Comment by ShawkMusic** [comment]
> @ShawkMusic Increased the speed limit on the dev branch. This feature might not be released for a while I'm not sure.

Nice. Why might this not be released for a while?

**Comment by VampireChicken12** [comment]
> > @ShawkMusic Increased the speed limit on the dev branch. This feature might not be released for a while I'm not sure.
> 
> Nice. Why might this not be released for a while?

Released in version 1.27.0 @ShawkMusic
