### ISSUE TITLE
[Bug] Theater mode live chat breaks with extension

### ISSUE THREAD

**Issue by shrublet** [YouTube-Enhancer/extension#699]
**Describe the bug**
On livestreams with chat available, when theater mode is enabled, the video spans the entire horizontal length instead of putting the live chat on the right side.

**To Reproduce**

1. Go to any live stream with chat (example: https://www.youtube.com/watch?v=jfKfPfyJRdk)
2. Enable theater mode

**Expected behavior**
The chat should be on the right side instead of being pushed down.

**Screenshots**

https://github.com/user-attachments/assets/73e3061d-03d5-4291-a94f-6ba1d9c809f0

**Desktop (please complete the following information):**

- OS: Linux Fedora 41 (GNOME)
- Browser: Firefox
- Version: 132.0.2

**Additional context**
Happens with default configuration, and I also tried disabling auto theater-mode, auto expand video, and use all available space features under the "Appearance" section. I tried disabling all other extensions with the same behavior still being exhibited as well.

**Comment by VampireChicken12** [comment]
@shrublet You are using the wrong extension. I can't help with this issue sorry.

**Comment by VampireChicken12** [comment]
@shrublet it's okay, thank you I appreciate the kind words. Yeah it is good. That's good. You are welcome.
