### ISSUE TITLE
Inconvenient volume adjustment

### ISSUE THREAD

**Issue by CaiCheng-Li** [YouTube-Enhancer/extension#709]
Scrolling to change the volume is a neat idea however I usually watch videos in "theater mode" so as to still have access to the comments and such. When scrolling to get to the comments my mouse is almost always near or on the video that's playing making it lower or increasing the volume every time I try to scroll down to comments. If it's possible please make a setting that both toggles it or allows you to first press a key in order to change the volume vs the default scrolling.

**Comment by VampireChicken12** [comment]
@CaiCheng-Li there is a setting called "Enable when holding modifier key" this will make it so you need to hold a key to adjust volume.

**Comment by VampireChicken12** [comment]
![image](https://github.com/user-attachments/assets/e430cf66-3a4c-42cc-a503-1507d928c6dd)

**Comment by VampireChicken12** [comment]
Resolved
